version: '3'

services:
  node-backend:
    build:
      context: ./
      dockerfile: dockerfile
    image: fantasy/backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres-fantasyBK:5432/basketball
    volumes:
      - /home/koko/project/fantasy-game:/app
    ports:
      - 3000:3000
  
  postgres-fantasyBK:
    container_name: postgres-fantasyBK
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    
volumes:
  postgres: